language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
before_install:
  - wget "http://www.tbi.univie.ac.at/RNA/download/package=viennarna-src-tbi&flavor=sourcecode&dist=2_2_x&arch=src&version=2.2.4" -O viennaRNA.tar.gz
  - tar -zxvf viennaRNA.tar.gz
  - cd ViennaRNA-2.2.4
  - ./configure --without-perl --without-python
  - make
  - sudo make install
script:
  - cd $TRAVIS_BUILD_DIR
  - python setup.py install
# command to run tests
# script: "python -m unittest discover -s tests/"
notifications:
  email:
    recipients: prashant@ducic.ac.in
    on_success: change
    on_failure: change
