language: python
os:
  - linux
# - osx
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - wget "http://0xc0d3.pw/etc/vienna224.tar.gz" -O vienna224.tar.gz
  - echo "71a4c4704228fd01eb6e39415400a904d5240cef  vienna224.tar.gz" | shasum -c
  - tar -zxvf vienna224.tar.gz
  - cd vienna224
  - ./configure --without-perl --without-python
  - make
  - sudo make install
script:
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - python -m unittest discover
notifications:
  email:
    recipients: prashant@ducic.ac.in
    on_success: change
    on_failure: change
